# Generated by Django 4.2.4 on 2024-01-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblLogin',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
