# Generated by Django 4.2.4 on 2024-01-31 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_tbllogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblstudentregistration',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='tblstudentregistration',
            name='pincode',
        ),
    ]
