# Generated by Django 4.2.4 on 2024-02-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_remove_tblstudentregistration_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblStuCourse',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('mobileno', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=100)),
                ('regdate1', models.DateField(auto_now=True)),
                ('modifiedBy', models.CharField(blank=True, max_length=15, null=True)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
