# Generated by Django 4.2.4 on 2024-02-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0004_tblstucourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblcourse',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=30)),
                ('isActive', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('CreatedBy', models.CharField(blank=True, max_length=15, null=True)),
                ('CreatedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblMaterial',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Topic', models.CharField(max_length=100)),
                ('VideoMaterial', models.FileField(blank=True, null=True, upload_to='Video/')),
                ('TextMaterial', models.FileField(blank=True, null=True, upload_to='TextMaterial/')),
                ('Program', models.FileField(blank=True, null=True, upload_to='Program/')),
                ('isActive', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('CreatedBy', models.CharField(blank=True, max_length=15, null=True)),
                ('CreatedDate', models.DateField(auto_now=True)),
                ('ModifiedBy', models.CharField(blank=True, max_length=15, null=True)),
                ('ModifiedDate', models.DateField(auto_now=True)),
            ],
        ),
    ]
