# Generated by Django 4.2.4 on 2024-02-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0005_tblcourse_tblmaterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblcourse',
            old_name='CourseName',
            new_name='course',
        ),
        migrations.AddField(
            model_name='tblmaterial',
            name='course',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
