# Generated by Django 4.2.4 on 2024-02-19 07:17

import LMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0006_rename_coursename_tblcourse_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblstudentregistration',
            name='file',
        ),
        migrations.AlterField(
            model_name='tblmaterial',
            name='VideoMaterial',
            field=models.FileField(null=True, upload_to=LMS.models.upload_video_to, validators=[LMS.models.validate_video_file]),
        ),
    ]
