# Generated by Django 4.2.4 on 2024-02-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0007_remove_tblstudentregistration_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcourse',
            name='coursefee',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
