# Generated by Django 4.2.4 on 2024-02-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0008_tblcourse_coursefee'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblAdminlogin',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=30)),
                ('regdate1', models.DateField(auto_now=True)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
