# Generated by Django 5.0.1 on 2024-02-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0009_tbladminlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblStuquery',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=25)),
                ('query', models.CharField(max_length=500)),
                ('queryans', models.CharField(max_length=500)),
                ('CreatedDate', models.DateField(auto_now=True)),
                ('ModifiedBy', models.CharField(blank=True, max_length=15, null=True)),
                ('ModifiedDate', models.DateField(auto_now=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
