# Generated by Django 5.0.1 on 2024-03-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0011_tblempdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblempdetails',
            name='Modifyby',
        ),
    ]
