# Generated by Django 5.0.1 on 2024-03-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0012_remove_tblempdetails_modifyby'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblempdetails',
            name='Course',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
