# Generated by Django 5.0.1 on 2024-03-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0013_tblempdetails_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblEmpCourse',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ContactNo', models.CharField(max_length=20)),
                ('Course', models.CharField(max_length=50, null=True)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
