# Generated by Django 5.0.1 on 2024-03-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0014_tblempcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudentregistration',
            name='coursefee',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
