# Generated by Django 5.0.1 on 2024-03-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0015_tblstudentregistration_coursefee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstuquery',
            name='mobileno',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
