# Generated by Django 5.0.1 on 2024-03-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0016_tblstuquery_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstucourse',
            name='name',
            field=models.CharField(default=9898, max_length=200),
            preserve_default=False,
        ),
    ]
