# Generated by Django 5.0.1 on 2024-04-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0017_tblstucourse_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstuquery',
            name='username',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
